name: Terraform Deployment

on:
  push:
    branches:
      - tuesday_githubactions  

jobs:
  terraform:
    runs-on: ubuntu-latest

     env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
      AWS_SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6  

      - name: Initialize Terraform
        run: terraform init
        

      - name: Plan Terraform Changes
        run: terraform plan -var-file=vars.tfvars
        

      - name: Apply Terraform Changes
        run: terraform apply -var-file=vars.tfvars
        

